def configure(ctx):
    pass


def build(ctx):
    ctx.install_files('${PREFIX}', ctx.path.ant_glob('*.py'))
    ctx.install_files('${PREFIX}', ctx.path.ant_glob('*.ttf'))
    ctx.install_files('${PREFIX}', ctx.path.ant_glob('site.conf.sample'))
